import './globals.css'
import { Nunito } from 'next/font/google'
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/modals/LoginModal';
import RegisterModal from './components/modals/RegisterModal';
import getCurrentUser from './actions/getCurrentUser';
import ClientOnly from './components/ClientOnly';
import Navbar from './components/navbar/Navbar';
import { Providers } from './redux/provider';

const font = Nunito({ subsets: ['latin'], });

export const metadata = {
  title: 'ordoICT',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="ko">
      <body className={font.className}>
      <Providers>
          <ClientOnly>
            <ToasterProvider />
            <LoginModal />{/* 로그인 팝업 */}
            <RegisterModal />{/* 회원가입 팝업 */}
            <Navbar currentUser={currentUser} />{/* 상단 메뉴 */}
          </ClientOnly>
          <div className="pb-20 pt-28">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}