import getCurrentUser from './actions/getCurrentUser';
import ClientOnly from './components/ClientOnly';
import Navbar from './components/navbar/Navbar';

import './globals.css'
// import { Inter } from 'next/font/google'
import { Nunito } from 'next/font/google'
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/modals/LoginModal';
import RegisterModal from './components/modals/RegisterModal';
// import { useAppDispatch, useAppSelector } from './Store/hooks';
// import { setAccess_Token } from './util/cookies/cookieStore';
// import 'bootstrap/dist/css/bootstrap.min.css'

// const inter = Inter({ subsets: ['latin'] });
const font = Nunito({ subsets: ['latin'], });

export const metadata = {
  title: 'ordoICT',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const currentUser = await getCurrentUser();

console.log(currentUser);


  return (
    <html lang="ko">

      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModal />{/* 로그인 팝업 */}
          <RegisterModal />{/* 회원가입 팝업 */}
          <Navbar currentUser={currentUser} />{/* 상단 메뉴 */}
        </ClientOnly>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>

    </html>
  )
}